/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_JNIDemo */

#ifndef _Included_com_JNIDemo
#define _Included_com_JNIDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_JNIDemo
 * Method:    testHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_JNIDemo_testHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
